Repository build-server-protocol/build-server-protocol, pull requests merged in 2018-11, with the labels that each got.

#49 Describe task notifications and how they are used with requests
  bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
  bsp4j/src/main/java/ch/epfl/scala/bsp4j/TaskDataKind.java
  bsp4j/src/main/java/ch/epfl/scala/bsp4j/TestStatus.java
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/CompileTask.java
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/RunParams.java
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TaskFinishParams.java
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TaskProgressParams.java
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TaskStartParams.java
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TestFinished.java
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TestStarted.java
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TestTask.java
  bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
  docs/bsp.md
Labels: spec

#53 Add protocol to discover and connect to BSP servers
  bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
  bsp4j/src/main/java/ch/epfl/scala/bsp4j/ScalaExtension.xtend
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/InitializeBuildParams.java
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/InitializeBuildResult.java
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/RunParams.java
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/ScalaTestParams.java
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TestParams.java
  bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
  docs/bsp.md
  tests/src/test/scala/tests/BloopSuite.scala
  tests/src/test/scala/tests/TypoSuite.scala
Labels: connection protocol, spec

#71 Add `reset` to `buildTarget/publishDiagnostics`
  bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
  bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/PublishDiagnosticsParams.java
  bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
  docs/bsp.md
Labels: enhancement, spec
